# Proje Tanimi
### Projenin Amaci
Bu proje, Pandas kütüphanesini kullanarak müşteri harcama verilerini analiz etmeyi amaçlamaktadır. Gerçek hayattaki tablo yapısını temsil eden müşteri verileri üzerinde Series ve DataFrame yapıları kullanılarak veri manipülasyonu yapılacaktır.

### Pandas Neden Kullanilir?
Pandas, tablo şeklindeki verileri analiz etmek ve düzenlemek için kullanılan bir Python kütüphanesidir. Excel benzeri satır–sütun yapısıyla çalışır ve farklı veri tiplerini
(sayı, metin, tarih vb.) aynı tabloda tutabilir. Veri temizleme, filtreleme, gruplama ve özet çıkarma işlemlerini kolay ve hızlı bir şekilde yapmayı sağlar.

### Kapsanan Pandas Konulari
Bu projede **yalnızca** aşağıdaki Pandas başlıkları kullanılacaktır:
* Pandas giriş
* Series
* Series özellikleri
* DataFrame
* DataFrame indeksler
* İndeks değiştirme
* Multi-index

In [33]:
# 2.Importing pandas and creating series for monthly expenses
import pandas as pd
import numpy as np

months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
spending = np.random.randint(12500, 800000, len(months))

monthly_spending = pd.Series(spending, index=months)

print(f"Months: {months}")
print(f"\nExpenses: {spending}")
print(f"\nMonthly Expenses: \n{monthly_spending}")

Months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

Expenses: [ 77662 495515 628210 160182 366411 377661 102877 235223 543337 696179
 275376 554457]

Monthly Expenses:
Jan     77662
Feb    495515
Mar    628210
Apr    160182
May    366411
Jun    377661
Jul    102877
Aug    235223
Sep    543337
Oct    696179
Nov    275376
Dec    554457
dtype: int64

In [34]:
# 3.Characteristics of Series
values_of_monthly_spending = monthly_spending.values
indexes_of_monthly_spending = monthly_spending.index
type_of_monthly_spending_series = monthly_spending.dtype
avg_monthly_spending = round(monthly_spending.mean(), 2)

print(f"Values of monthly spending: {values_of_monthly_spending}")
print(f"Index Of Monthly Expenses: {indexes_of_monthly_spending}")
print(f"Type of Monthly spending: {type_of_monthly_spending_series}")
print(f"Average Monthly spending: {avg_monthly_spending}")

Values of monthly spending: [ 77662 495515 628210 160182 366411 377661 102877 235223 543337 696179
 275376 554457]
Index Of Monthly Expenses: Index(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct',
       'Nov', 'Dec'],
      dtype='object')
Type of Monthly spending: int64
Average Monthly spending: 376090.83

In [35]:
# 4.Creating a dataframe
customer_names = ["Joe","Johny","Brad","Chris","Jennifer","Sam","George","Natalie","Sally","Michael","Christina","Marry"]
cities = ["New York","Los Angeles","Chicago","Houston","Phoenix","Philadelphia","San Antonio","San Diego","Dallas","San Jose","Austin","Jacksonville"]
monthlySpendings = np.random.randint(12500, 800000, len(customer_names))
membershipTypes = ["Basic","Standard","Premium","Gold","Silver","Platinum","VIP","Student","Family","Corporate","Trial","Lifetime"]

data = {
    "CustomerName": customer_names,
    "City": cities,
    "MonthlySpending" : monthlySpendings,
    "MembershipType": membershipTypes,
}
df = pd.DataFrame(data)
df

   CustomerName          City  MonthlySpending MembershipType
0           Joe      New York            40210          Basic
1         Johny   Los Angeles           467710       Standard
2          Brad       Chicago           687315        Premium
3         Chris       Houston           420180           Gold
4      Jennifer       Phoenix           260885         Silver
5           Sam  Philadelphia            86956       Platinum
6        George   San Antonio           258377            VIP
7       Natalie     San Diego           211898        Student
8         Sally        Dallas            83817         Family
9       Michael      San Jose           134372      Corporate
10    Christina        Austin           362228          Trial
11        Marry  Jacksonville            69753       Lifetime

In [36]:
# 5.Indexing DataFrame
new_index = df.set_index("CustomerName")

print(f"New Index: \n{new_index}")
print(f"\nChoosing a row via index: \n{new_index.loc['Joe']}")

New Index:
                      City  MonthlySpending MembershipType
CustomerName
Joe               New York            40210          Basic
Johny          Los Angeles           467710       Standard
Brad               Chicago           687315        Premium
Chris              Houston           420180           Gold
Jennifer           Phoenix           260885         Silver
Sam           Philadelphia            86956       Platinum
George         San Antonio           258377            VIP
Natalie          San Diego           211898        Student
Sally               Dallas            83817         Family
Michael           San Jose           134372      Corporate
Christina           Austin           362228          Trial
Marry         Jacksonville            69753       Lifetime

Choosing a row via index:
City               New York
MonthlySpending       40210
MembershipType        Basic
Name: Joe, dtype: object

In [37]:
# 6.Changing Index
index_reset = new_index.reset_index()

setting_new_index = index_reset.set_index("City")

print(f"Index was reset: \n{index_reset}")
print(f"\nSetting new index: \n{setting_new_index}")

Index was reset:
   CustomerName          City  MonthlySpending MembershipType
0           Joe      New York            40210          Basic
1         Johny   Los Angeles           467710       Standard
2          Brad       Chicago           687315        Premium
3         Chris       Houston           420180           Gold
4      Jennifer       Phoenix           260885         Silver
5           Sam  Philadelphia            86956       Platinum
6        George   San Antonio           258377            VIP
7       Natalie     San Diego           211898        Student
8         Sally        Dallas            83817         Family
9       Michael      San Jose           134372      Corporate
10    Christina        Austin           362228          Trial
11        Marry  Jacksonville            69753       Lifetime

Setting new index:
             CustomerName  MonthlySpending MembershipType
City
New York              Joe            40210          Basic
Los Angeles         Johny           467710       Standard
Chicago              Brad           687315        Premium
Houston             Chris           420180           Gold
Phoenix          Jennifer           260885         Silver
Philadelphia          Sam            86956       Platinum
San Antonio        George           258377            VIP
San Diego         Natalie           211898        Student
Dallas              Sally            83817         Family
San Jose          Michael           134372      Corporate
Austin          Christina           362228          Trial
Jacksonville        Marry            69753       Lifetime

In [38]:
# 7.Creating Multi Index
df_multi_index = df.set_index(["City","MembershipType"])
df_multi_index

                            CustomerName  MonthlySpending
City         MembershipType
New York     Basic                   Joe            40210
Los Angeles  Standard              Johny           467710
Chicago      Premium                Brad           687315
Houston      Gold                  Chris           420180
Phoenix      Silver             Jennifer           260885
Philadelphia Platinum                Sam            86956
San Antonio  VIP                  George           258377
San Diego    Student             Natalie           211898
Dallas       Family                Sally            83817
San Jose     Corporate           Michael           134372
Austin       Trial             Christina           362228
Jacksonville Lifetime              Marry            69753

In [39]:
# 8.General Summary
number_of_customers = df.shape[0]
highest_monthly_spending = df["MonthlySpending"].max()

print(f"Number of customers: {number_of_customers}")
print(f"Highest monthly spending: {highest_monthly_spending}")

Number of customers: 12
Highest monthly spending: 687315